---
scenario:
  map: 'Town07'

  actors:
    - filter: 'vehicle.*'
      attributes:
        number_of_wheels: 4
      traffic: 'dense'
      autopilot: True

    - filter: 'walker.*'
      traffic: 'light'
      autopilot: True

  synchronous_mode: True
  no_rendering_mode: True
  fixed_delta_seconds: 0.1
